// @ts-check
// command: prove a published package installs and works standalone, by actually installing and running it
// Can a consumer install this package and use it? Answered by doing it.
//
//   node packages/guards/src/isolation-gate.ts packages/evidence [more...]
//   npm run gate:isolation
//
// ## Why a workspace cannot answer this
//
// A workspace install resolves everything by symlink, with the repo root as the cwd, so it is
// STRUCTURALLY INCAPABLE of detecting the failures that matter to a consumer (ADR 0007):
//
// - **phantom dependencies** — npm's hoisting makes an undeclared import resolve anyway;
// - **cwd-relative resolution** — `local-judge.ts` resolved the scorer as `".venv/bin/python"` and
//   `"scripts/score-screenreader-model.py"`, which work only when the cwd is the repo root;
// - **files dropped by `"files"`** — `.ps1`, `.cmd` and `.safetensors` payloads are exactly what an
//   allow-list loses silently;
// - **`"exports"` subpaths that do not resolve** the paths the README tells people to import.
//
// So the gate packs the package, installs the tarball into a fresh directory OUTSIDE the repository, and
// runs the package's own smoke test there. Continuous Delivery's smoke-test-the-deployed-artefact
// discipline, applied to a tarball.
//
// ## Two package managers, on purpose (#2301)
//
// THE PACK HALF IS pnpm's AND THE CONSUMER HALF IS npm's. The release publishes with `pnpm publish`
// (changesets picks the tool from the workspace), so what a consumer receives is what `pnpm pack` makes:
// packing with anything else would check a tarball nobody publishes. But the person who runs
// `npm install a11ign` is not a pnpm user by assumption, so the tarballs are installed with NPM, into a
// directory that is not a workspace. A gate that installed with pnpm would prove the wrong thing: pnpm's
// stricter resolution is the point of packing with it, and the reason the install must not use it.
//
// **A THIRD CHECK LIVES BETWEEN THE TWO, and it exists because npm cannot be trusted to notice.** Every
// internal dependency in a packed `package.json` must carry a real range that the sibling being packed
// alongside actually SATISFIES, read out of the tarball and not out of the source. A `workspace:*` left in
// a tarball installs for nobody, and npm does say so. A range the sibling does NOT satisfy is worse: npm
// resolves it from the REGISTRY, silently, and a consumer of the real release would run a different copy
// of `@a11ign/evidence` than the one this gate just tested (`packedRangeProblems`).
//
// ## One trap, learned the hard way
//
// **A pack includes untracked files** (`npm pack` always did; `pnpm pack` is checked for it in
// `isolation-gate-refuses.test.ts`). A tarball built on a machine that happens to hold a missing file
// contains it, which is exactly how `scripts/score-screenreader-model.py` — the default judge backend —
// went missing from the repo for the project's whole life while every local run succeeded.
// `packedButUntracked` below now catches that class: a packed file git neither tracks nor ignores exists
// only on the machine that packed it. `src/referenced-scripts.test.ts` still covers the other half by
// asserting tracked-ness.
//
// **SCOPE — the sentence the next reader needs.** That check can only bite on a package whose `"files"`
// list ships SOURCE, and there are three: `nvda-worker` (`src`), `scorer` (`bin`, `python`,
// `models/screenreader-scorer`) and `worker-fleet` (`src/local-worker`, `src/provisioning`). The other
// three published packages ship `["dist", ...]` — gitignored build output, regenerated by `npm run build`
// — so a source file somebody forgot to commit is never packed there at all and this gate is
// structurally silent about it. That is not a gap to close: it is where the defect can happen, and it is
// where the historical one did (`python/` in `scorer`). Proved by planting a file in `evidence` and
// watching nothing fire — a bite-proof that fails usefully rather than one that flatters the guard.
import { execFileSync } from "node:child_process";
import { sandboxGitEnv } from "./git-env.ts";
import { existsSync, mkdtempSync, copyFileSync, readFileSync, rmSync, readdirSync, realpathSync }
  from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve, basename, dirname } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
// RELATIVE, for `ci-changed.ts`'s documented reason: this file is in that script's import graph, and
// `ci.yml`'s `changed` job runs no `npm ci` — it decides whether anything else installs at all. A package
// specifier here dies before the workflow starts.
import { refuseUnknownFlags } from "./cli-flags.ts";
// STAYS npm for the consumer half (`no-npm-spawn.test.ts` pins this file by name; the header's "Two package managers, on purpose" says why):
// the tarballs are installed as `npm install a11ign` would, outside any workspace.
import { npmCliInvocation, pnpmCliInvocation } from "./npm-cli-executable.ts";

export const SMOKE = "isolation-smoke.ts";

/** Somewhere that is definitively not inside the repo, so nothing can resolve by accident. */
const consumerDir = () => mkdtempSync(join(tmpdir(), "a11y-isolation-"));

/**
 * @param {string} command
 * @param {string[]} args
 * @param {string} cwd
 * @param {Record<string, string | undefined>} [env]
 */
function run(command: string, args: string[], cwd: string, env?: Record<string, string | undefined>) {
  return execFileSync(command, args,
    { cwd, encoding: "utf8", stdio: ["ignore", "pipe", "pipe"], env: env ? { ...process.env, ...env } : undefined });
}

/**
 * `npm <args>`, via `run` above, WITHOUT ever spawning `npm` itself -- #492.
 * @param {string[]} args
 * @param {string} cwd
 * @param {Record<string, string | undefined>} [env]
 */
function runNpm(args: string[], cwd: string, env?: Record<string, string | undefined>) {
  const npm = npmCliInvocation("npm", args);
  return run(npm.command, npm.args, cwd, env);
}

/**
 * `pnpm <args>`, the same way and for the same reason -- and the ONE place this gate packs from (#2301).
 * @param {string[]} args
 * @param {string} cwd
 * @param {Record<string, string | undefined>} [env]
 */
function runPnpm(args: string[], cwd: string, env?: Record<string, string | undefined>) {
  const pnpm = pnpmCliInvocation(args);
  return run(pnpm.command, pnpm.args, cwd, env);
}

/**
 * The JSON object `pnpm pack --json` prints, out of an output that begins with the package's own lifecycle
 * banner: a `prepack` script (every package here has one, `tsc --build`) writes `> name@version prepack`
 * to STDOUT ahead of the JSON, so the output is not itself parseable. The object starts at the first line
 * that is exactly `{`, and the nested `{`s of its `files` list are indented, so that line is unambiguous.
 * @param {string} output
 * @returns {{ name: string, version: string, filename: string, files?: { path: string }[] }}
 */
function packJson(output: string): { name: string; version: string; filename: string; files?: { path: string; }[]; } {
  const start = output.startsWith("{") ? 0 : output.indexOf("\n{\n") + 1;
  if (start === 0 && !output.startsWith("{")) throw new Error(`pnpm pack printed no JSON object: ${output.slice(0, OUTPUT_PREVIEW)}`);
  return JSON.parse(output.slice(start));
}

type PackedManifest = { name: string; version: string; dependencies?: Record<string, string>;
  peerDependencies?: Record<string, string>; optionalDependencies?: Record<string, string> };

/**
 * `[major, minor, patch]` of a plain `x.y.z` version, or `null` for anything else (a prerelease, a range).
 * @param {string} text
 * @returns {[number, number, number] | null}
 */
function parseVersion(text: string): [number, number, number] | null {
  const match = /^(\d+)\.(\d+)\.(\d+)$/.exec(text);
  return match ? [Number(match[1]), Number(match[2]), Number(match[3])] : null;
}

/** `~1.2.3` holds major and minor fixed. */
const TILDE_FIXES = 2;

/** How much of a packer's unparseable output an error carries: enough to recognise it, not all of it. */
const OUTPUT_PREVIEW = 200;

/** @param {number[]} a @param {number[]} b */
const compareVersions = (a: number[], b: number[]) => a[0] - b[0] || a[1] - b[1] || a[2] - b[2];

/**
 * DOES `version` SATISFY `range`? -- for the four spellings this repository's manifests use, and `null` for
 * every other, so an unfamiliar range is reported as UNVERIFIABLE rather than assumed satisfied. `semver` is
 * not a dependency of this package (an undeclared import is exactly what this gate exists to catch), and
 * `changeset version` writes only these: an exact `x.y.z`, or `^`/`~`/`>=` in front of one.
 *
 * `^` keeps the left-most non-zero part fixed (`^0.1.2` is `>=0.1.2 <0.2.0`, `^0.0.3` is exactly `0.0.3`),
 * which is what makes a `0.x` package's caret narrower than a `1.x` one's and is the easy thing to get wrong.
 * @param {string} version
 * @param {string} range
 * @returns {boolean | null}
 */
export function satisfies(version: string, range: string): boolean | null {
  const have = parseVersion(version);
  const operator = /^(\^|~|>=)?/.exec(range)?.[1] ?? "";
  const bound = parseVersion(range.slice(operator.length));
  if (have === null || bound === null) return null;
  const atLeast = compareVersions(have, bound) >= 0;
  if (operator === ">=") return atLeast;
  if (operator === "") return compareVersions(have, bound) === 0;
  const fixed = operator === "~" ? TILDE_FIXES : bound.findIndex((part) => part !== 0) + 1 || bound.length;
  return atLeast && have.slice(0, fixed).every((part, i) => part === bound[i]);
}

/**
 * What is wrong with the internal (`@a11ign/*`) ranges in these packed manifests -- READ OUT OF THE TARBALLS
 * (`tar -xOf <tarball> package/package.json`), never out of the source, because the source is not what a
 * consumer receives: `workspace:*` is legal in a source manifest and is rewritten (or, when a packer forgets,
 * NOT rewritten) on the way into the tarball.
 *
 * Three ways to be wrong, each reported with the package that carries it:
 * - the `workspace:` protocol, which installs for nobody;
 * - a range that is not one of the forms `satisfies` can read, which nobody can check;
 * - a range the sibling packed BESIDE it does not satisfy, which npm answers from the registry without a word.
 * @returns {string[]}
 */
export function packedRangeProblems(manifests: PackedManifest[]): string[] {
  const versions = new Map(manifests.map((manifest) => [manifest.name, manifest.version]));
  /** @type {string[]} */
  const problems: string[] = [];
  for (const manifest of manifests) {
    const declared = { ...manifest.dependencies, ...manifest.peerDependencies, ...manifest.optionalDependencies };
    for (const [dependency, range] of Object.entries(declared)) {
      if (!dependency.startsWith("@a11ign/")) continue;
      const where = `${manifest.name} -> ${dependency}@${range}`;
      const sibling = versions.get(dependency);
      if (range.startsWith("workspace:")) problems.push(`${where}: the workspace: protocol reached the tarball`);
      else if (sibling !== undefined && satisfies(sibling, range) === null) problems.push(`${where}: not a range this gate can check`);
      else if (sibling !== undefined && satisfies(sibling, range) === false) {
        problems.push(`${where}: packed beside it is ${sibling}, which that range excludes -- npm would fetch the registry's copy`);
      }
    }
  }
  return problems;
}

/**
 * The internal ranges one tarball declares, as `@a11ign/x@range`, for the PASS line: "the ranges are fine" is
 * a claim, and the line that carries it should carry what was read, so a reader can see it was not vacuous.
 * @returns {string}
 */
function internalRangesNote(manifest: PackedManifest): string {
  const declared = { ...manifest.dependencies, ...manifest.peerDependencies, ...manifest.optionalDependencies };
  const internal = Object.entries(declared).filter(([dependency]) => dependency.startsWith("@a11ign/"))
    .map(([dependency, range]) => `${dependency}@${range}`);
  return internal.length ? `; tarball ranges: ${internal.join(", ")}` : "; no internal dependencies";
}

function tarballManifest(tarball: string): PackedManifest {
  return JSON.parse(run("tar", ["-xOf", tarball, "package/package.json"], dirname(tarball)));
}

/**
 * A caret or tilde range is how a package consumes one that PUBLISHES FROM ANOTHER REPOSITORY (#3125: `cli` takes `@a11ign/documents`
 * by `^0.1.0`). With no sibling directory here, such a range names nothing to pack and npm fetches it from the
 * registry, where it exists; a sibling that DOES exist is packed and range-checked whatever the range's spelling. A typo'd one still fails, at the gate's install, with the E404 it would give a consumer.
 */
const REGISTRY_RANGE = /^[\^~]\d/;

/**
 * Sibling packages this one depends on, as directories, transitively.
 *
 * Only `@a11ign/*` — everything else comes from the registry, which is the point of the gate: a
 * dependency npm can actually resolve is not the failure mode being tested.
 * @param {string} packageDir
 * @param {Set<string>} [seen]
 * @returns {string[]}
 */
export function internalDependencies(packageDir: string, seen: Set<string> = new Set()): string[] {
  const manifest = JSON.parse(readFileSync(join(resolve(packageDir), "package.json"), "utf8"));
  const wanted = { ...manifest.dependencies, ...manifest.peerDependencies };
  const optional = manifest.peerDependenciesMeta ?? {};
  /** @type {string[]} */
  const dirs: string[] = [];
  for (const dependency of Object.keys(wanted)) {
    if (!dependency.startsWith("@a11ign/") || seen.has(dependency)) continue;
    if (optional[dependency]?.optional && !existsSync(siblingDir(packageDir, dependency))) continue;
    seen.add(dependency);
    const dir = siblingDir(packageDir, dependency);
    if (!existsSync(join(dir, "package.json")) && REGISTRY_RANGE.test(wanted[dependency])) continue;
    if (!existsSync(join(dir, "package.json"))) {
      throw new Error(`${manifest.name} depends on ${dependency}, which is not a package in this repo`);
    }
    dirs.push(dir, ...internalDependencies(dir, seen));
  }
  return dirs;
}

/** The directory beside the package asking whose manifest NAMES `dependency`. Found by name, not spelled from
 * it: `packages/pdf` is `@a11ign/documents` (#2705), and a directory spelled from the name did not exist. A
 * name matching no directory falls back to the spelled one, so the caller's "not a package in this repo"
 * refusal still fires with the path it would have looked at.
 * @type {(packageDir: string, dependency: string) => string} */
const siblingDir: (packageDir: string, dependency: string) => string = (packageDir, dependency): string => {
  const packagesDir = join(resolve(packageDir), "..");
  const named = readdirSync(packagesDir).find((entry) => {
    const manifest = join(packagesDir, entry, "package.json");
    return existsSync(manifest) && JSON.parse(readFileSync(manifest, "utf8")).name === dependency;
  });
  return join(packagesDir, named ?? dependency.slice("@a11ign/".length));
};


/**
 * The names `npm` will put on a consumer's PATH, for either spelling of `bin`.
 *
 * The string shorthand (`"bin": "./cli.mjs"`) links ONE name — the package name with any scope dropped —
 * so `@a11ign/screenreader-fleet` would link `worker-fleet`. Reading only the object form would report a package
 * with the shorthand as declaring no bins at all, which is the same "an absence reads as a pass" shape the
 * missing-smoke-test branch above exists to refuse.
 *
 * @param {{ name?: string, bin?: string | Record<string, string> }} manifest
 * @returns {string[]}
 */
export function declaredBins(manifest: { name?: string; bin?: string | Record<string, string>; }): string[] {
  if (!manifest.bin) return [];
  if (typeof manifest.bin === "string") return [(manifest.name ?? "").split("/").pop() ?? ""];
  return Object.keys(manifest.bin);
}

/**
 * Declared bins the consumer did NOT get — read from the consumer's own `node_modules/.bin`, never from
 * the manifest or the tarball listing.
 *
 * **`npm install` creates a shim only for a bin whose target it actually received, and creates NOTHING,
 * silently, for one it did not.** Measured 2026-09-12 against a throwaway package declaring two bins, one
 * packed and one not: the install printed no warning and exited 0, and `.bin` simply held one entry.
 * Every field in the manifest was correct; the consumer's failure is `command not found` at first use.
 *
 * That is why this asks the consumer rather than comparing `bin` against `packedFiles`. The tarball
 * listing would answer a NEIGHBOURING question — "is the file in the archive" — and npm's linking rules
 * (the shorthand above, a scope dropped from the name, a target outside the package root) sit between
 * that answer and the one a consumer lives with. `existsSync` on a dangling symlink is false, so a shim
 * npm created pointing at nothing counts as missing here too, which is the right answer for both.
 *
 * **This says the bin is REACHABLE, not that it WORKS.** Running them is not available to this gate as a
 * blanket rule: `a11ign-nvda-worker` starts a server and `a11ign-worker-ctl` drives a VM, so a gate that
 * executed every declared bin would be a gate nobody could run offline. A package that wants its bin
 * EXECUTED says so in its own `isolation-smoke.ts`, which `packages/cli`'s already does — through the
 * `.bin` shim, for the documented reason that a realpath'd path misses the symlink case.
 *
 * @param {string} consumer the throwaway install directory
 * @param {{ name?: string, bin?: string | Record<string, string> }} manifest
 * @returns {string[]}
 */
export function missingBinShims(consumer: string, manifest: { name?: string; bin?: string | Record<string, string>; }): string[] {
  return declaredBins(manifest).filter((binName) => !existsSync(join(consumer, "node_modules", ".bin", binName)));
}

/**
 * What `pnpm pack --dry-run` actually ships for one package, as a `Set` of paths relative to the package
 * root. This is this repo's one real answer to "can a consumer install this" / "does this reach a
 * consumer", and `scripts/ci-changed.ts`'s changeset gate imports it directly rather than carrying a
 * second copy — two derivations of what ships, guarding the same promise, is exactly the fact-stated-
 * twice shape this file's own header names for `referenced-scripts.test.ts`.
 *
 * @param {string} dir the package directory
 * @returns {Set<string>}
 */
export function packedFiles(dir: string): Set<string> {
  // `--json` gives the file list without unpacking; `--dry-run` so nothing is written. `sandboxGitEnv()`
  // even though this spawns `pnpm`, not `git` — a pack walks the package looking for a `.git` to
  // decide what "untracked" means for its own purposes, so an inherited `GIT_DIR` is the identical
  // redirection risk `git-env.ts`'s own header names, one process removed.
  //
  // PACKED BY pnpm SINCE #2301, because the release publishes with `pnpm publish`, which packs with the same
  // code: a file list derived by a DIFFERENT tool would answer "what would npm ship" about a tarball
  // nobody publishes. (Every other place that asks what ships -- `ci-changed.ts`'s changeset gate -- asks
  // this function, so the move reaches all of them at once.)
  const listing = packJson(runPnpm(["pack", "--dry-run", "--json"], dir, sandboxGitEnv()));
  return new Set((listing.files ?? []).map((f) => f.path));
}

/**
 * Would this tarball carry a file that is NOT COMMITTED? — the half this gate has always disclaimed.
 *
 * The header above names the trap and stops short of checking it: *"`npm pack` includes untracked files. A
 * tarball built on a machine that happens to hold a missing file contains it, which is exactly how
 * `scripts/score-screenreader-model.py` — the default judge backend — went missing from the repo for the
 * project's whole life while every local run succeeded."* It then says this gate proves *installability,
 * not completeness of the repo*, and delegates the other half to `referenced-scripts.test.ts`.
 *
 * **That delegation covers scripts a file REFERENCES. It does not cover a file the tarball SHIPS.** A
 * package can pack an untracked file nothing references by name — a build artefact, a scratch model, a
 * fixture someone forgot to `git add` — and every clean-room install on that machine passes while the
 * published tarball is missing it. The gate is the only place that has the packed file list in its hands,
 * so it is the only place the question is cheap to ask.
 *
 * **PUBLISHED PACKAGES ONLY, and that is not a shortcut.** A private package is never installed by anyone,
 * so an untracked file in one cannot reach a consumer. Measured on this tree 2026-09-06: exactly one
 * untracked file existed under `packages/`, in `nvda-speech`, which is `private: true` — so a local pack
 * and a tracked pack were identical, and nothing enforced that they would stay so.
 *
 * Reported per package rather than thrown, so one dirty checkout names its own file instead of failing the
 * whole gate with a stack trace.
 *
 * @param {string} dir the package directory
 * @returns {string[]} packed paths that git does not track, relative to the package
 */
function packedButUntracked(dir: string): string[] {
  let packed;
  try {
    packed = [...packedFiles(dir)];
  } catch {
    return []; // cannot list -- claim nothing rather than invent a finding
  }
  // GIT_* SCRUBBED, and it is not ceremony here. This gate spawns commands with a temp directory as cwd,
  // and `cwd` LOSES TO THE ENVIRONMENT: an inherited GIT_DIR would point `git ls-files` at whatever
  // repository that variable names rather than the package in front of it -- the 2026-09-06 incident where
  // a hook-exported GIT_DIR redirected spawned git calls onto the real repo. `sandboxGitEnv` strips by
  // PREFIX, so a variable introduced tomorrow is caught without this file knowing its name.
  const tracked = new Set(run("git", ["ls-files"], dir, sandboxGitEnv()).split("\n").filter(Boolean));
  const candidates = packed.filter((path) => !tracked.has(path));
  if (!candidates.length) return [];
  // UNTRACKED IS NOT THE QUESTION -- IGNORED VERSUS FORGOTTEN IS, and the first version of this check got
  // that wrong and cried wolf on five of six packages. `dist/` is untracked by design: it is gitignored
  // build output, regenerated by `npm run build` from committed sources, and a published package SHIPS it.
  // Flagging that made the gate useless, which is the "guard that fails on correct input gets switched
  // off" shape this repo already pays for elsewhere.
  //
  // The dangerous file is the one that is untracked AND NOT IGNORED: nothing regenerates it and nobody
  // declared it disposable, so it exists only on the machine that packed it. That is exactly
  // `score-screenreader-model.py`, which every local run found and no clone contained.
  //
  // `git check-ignore` answers it directly rather than by matching path prefixes, so a change to
  // `.gitignore` cannot silently widen or narrow this. Exit 1 means "none of these are ignored", which is
  // the all-forgotten case rather than an error.
  /** @type {Set<string>} */
  let ignored: Set<string>;
  try {
    ignored = new Set(run("git", ["check-ignore", "--", ...candidates], dir, sandboxGitEnv()).split("\n").filter(Boolean));
  } catch {
    ignored = new Set(); // exit 1: nothing matched an ignore rule, so every candidate is forgotten
  }
  return candidates.filter((path) => !ignored.has(path));
}

/**
 * The bin half of a verdict, or `null` when every declared bin reached the consumer.
 *
 * Its own function because `checkIsolation` reads as a top-down narrative and this is one step of it --
 * and because the lint ceiling said so, which is the Stepdown Rule arriving as an error message.
 *
 * @param {string} consumer
 * @param {{ name?: string, bin?: string | Record<string, string> }} manifest
 * @param {string} name
 */
function unreachableBinVerdict(consumer: string, manifest: { name?: string; bin?: string | Record<string, string>; }, name: string) {
  const unreachable = missingBinShims(consumer, manifest);
  if (!unreachable.length) return null;
  return { ok: false, stage: "bin", name,
    detail: `installs, but ${unreachable.length} of ${declaredBins(manifest).length} declared bin(s) never `
      + `reach the consumer's PATH: ${unreachable.join(", ")} — npm links a shim only for a bin whose `
      + `target it received, and says nothing about one it did not` };
}

/**
 * What the PASS line says about bins, announced for the reason the private-package skip is announced
 * rather than silent: "no bins declared" and "every declared bin is reachable" are different facts, and a
 * verdict that renders them identically is a gate quietly covering less than its reader thinks.
 *
 * @param {{ name?: string, bin?: string | Record<string, string> }} manifest
 */
function binNote(manifest: { name?: string; bin?: string | Record<string, string>; }) {
  const declared = declaredBins(manifest);
  return declared.length ? `; ${declared.length} bin(s) on PATH` : "; no bins declared";
}

/**
 * The pack half and the install half, in that order, up to and including the bin check: `refused` is `null`
 * when the package is installed in `consumer` and every declared bin reached its PATH, otherwise the verdict
 * that says which stage refused; `note` says what the tarball's own internal ranges were. Its own function because it is the part of `checkIsolation` with two package
 * managers in it, and because the lint ceiling said so.
 *
 * @param {string} dir the package directory
 * @param {string} consumer the throwaway install directory
 * @param {{ name?: string, bin?: string | Record<string, string> }} manifest
 */
function packAndInstall(dir: string, consumer: string, manifest: { name?: string; bin?: string | Record<string, string>; }) {
  // Every sibling this package needs, packed too.
  //
  // Nothing is published, so npm cannot fetch `@a11ign/evidence` from the registry — it would fail
  // the install with E404 and the gate would report a broken package that is fine. npm 7+ also
  // auto-installs PEER dependencies, so a peer on an unpublished sibling fails the same way; that is why
  // peers are collected here as well.
  //
  // This is not a workaround, it is the composition the gate should have been testing all along: a
  // consumer installs `judge` AND the `scorer` it peers on, and the two have to work together outside the
  // workspace. `evidence` and `scorer` are leaves, so the omission was invisible until `judge` arrived.
  const tarballs = [dir, ...internalDependencies(dir)].map((source) =>
    join(consumer, basename(packJson(runPnpm(["pack", "--pack-destination", consumer, "--json"], source)).filename)));
  // BETWEEN THE TWO HALVES: what pnpm packed is read back before npm is asked to install any of it.
  const packed = tarballs.map(tarballManifest);
  const note = internalRangesNote(packed[0] as PackedManifest);
  const rangeProblems = packedRangeProblems(packed);
  if (rangeProblems.length) {
    return { note, refused: { ok: false, stage: "ranges", name: manifest.name,
      detail: `packs, but ${rangeProblems.length} internal range(s) in the tarballs are wrong: ${rangeProblems.join("; ")}` } };
  }
  runNpm(["init", "-y"], consumer);
  // `--no-workspaces` and absolute tarball paths: without them npm can walk UP from the temp directory
  // and re-attach to a workspace root, which would reintroduce exactly the symlink resolution the gate
  // exists to avoid.
  // `--omit=optional` because an OPTIONAL dependency is by definition not required to install and use the
  // package. The CLI declares `playwright` and `@axe-core/playwright` optional — the visual layer is opt-in
  // and loaded with a dynamic `import()` behind an availability check — so installing them here fetched
  // 25 MB of browser engine from the registry to run a renderer assertion that never opens a browser.
  // Measured: 7.1 s for the CLI against 2.2 s for a leaf package, and the gate could not run offline at all,
  // which is a Fast/Repeatable failure for no coverage in return. A package that genuinely NEEDS a dependency
  // must declare it as a dependency, and this gate exists to catch exactly that mistake.
  runNpm(["install", "--silent", "--no-workspaces", "--omit=optional", ...tarballs], consumer);
  // BEFORE the smoke test, because a bin a consumer cannot reach is a packaging defect whether or not
  // the library half works — and because most smoke tests import the package rather than spawning it,
  // so a green smoke run says nothing about `bin` at all. Measured on this repo the day the check was
  // written: pointing all five of `@a11ign/screenreader-fleet`'s bins at a file that does not exist left the
  // gate reporting `ok: true`.
  return { note, refused: unreachableBinVerdict(consumer, manifest, manifest.name ?? "") };
}

/**
 * Pack, install outside the repo, run the smoke test. Returns a verdict rather than throwing, because the
 * caller needs to report every package rather than stop at the first bad one.
 * @param {string} packageDir
 */
export function checkIsolation(packageDir: string) {
  const dir = resolve(packageDir);
  const smoke = join(dir, SMOKE);
  if (!existsSync(join(dir, "package.json"))) return { ok: false, stage: "setup", detail: `no package.json in ${dir}` };
  // A package with no smoke test cannot be gated, and silently passing it would make the gate a decoration.
  if (!existsSync(smoke)) return { ok: false, stage: "setup", detail: `no ${SMOKE} — the gate cannot verify this package` };

  const manifest = JSON.parse(readFileSync(join(dir, "package.json"), "utf8"));
  const name = manifest.name;
  const consumer = consumerDir();
  try {
    const { refused, note } = packAndInstall(dir, consumer, manifest);
    if (refused) return refused;
    copyFileSync(smoke, join(consumer, SMOKE));
    // `A11Y_ISOLATION_CONSUMER_DIR` carries the RAW `consumer` path — never realpath'd — because both
    // `execFileSync`'s `cwd` option and `require.resolve()` resolve symlinks, so a smoke test cannot
    // reconstruct the un-resolved path a real `npx`/global-install invocation would actually use once it
    // is already running with `consumer` as its (OS-canonicalised) working directory. A smoke test that
    // needs to reproduce a symlink-sensitive bug — the published bin silently doing nothing under
    // `os.tmpdir()`, which is `/var/folders/...` on macOS and itself a symlink to `/private/var/...` —
    // needs this to build the bin path the same way a real caller would.
    const output = run("node", [SMOKE], consumer, { A11Y_ISOLATION_CONSUMER_DIR: consumer });
    // INSTALLABLE AND COMPLETE ARE DIFFERENT CLAIMS, and this gate could only ever make the first. A
    // tarball that installs perfectly here can still be missing a file from the repository, because it was
    // packed from a working tree rather than from what is committed -- the score-screenreader-model.py
    // shape. Reported as a FAILURE rather than a note: a published tarball carrying a file no clone
    // contains is not a package that works, it is one that works on this machine.
    const untracked = packedButUntracked(dir);
    if (untracked.length) {
      return { ok: false, stage: "tracked", name,
        detail: `installs, but the tarball packs ${untracked.length} file(s) git does not track, so a `
          + `published build would not contain them: ${untracked.slice(0, 5).join(", ")}`
          + (untracked.length > 5 ? ` (+${untracked.length - 5} more)` : "") };
    }
    return { ok: true, stage: "smoke", name,
      detail: (output.trim().split("\n").slice(-1)[0] ?? "") + binNote(manifest) + note };
  } catch (error) {
    const e = error as { stderr?: string; stdout?: string; message?: string; status?: number };
    const stderr = String(e.stderr ?? e.stdout ?? e.message);
    // Exit 3 is the smoke test DECLINING a check this machine cannot make: guidepup refusing to import where
    // there is no screen reader, a macOS-only host-capacity read on Linux. That is a platform limit, not a
    // packaging defect, and it gets the same treatment private packages already get here — announced, not
    // counted as a pass, and not a failure.
    //
    // It was a failure until 2026-08-21, and the cost was not cosmetic: `gate:isolation` is the FIRST leg of
    // `release:gate`, so on the Linux control plane — the only machine with the Python venv the judge needs —
    // its failure stopped the chain and every model-quality gate behind it silently never ran.
    if (e.status === 3) {
      return { skipped: true, stage: "smoke", name, detail: stderr.trim().split("\n").slice(-1)[0] ?? "declined" };
    }
    // The first line that looks like a cause, not the whole npm essay.
    const cause = stderr.split("\n").find((l) => /Error|error|Cannot find|ERR_/.test(l))?.trim();
    return { ok: false, stage: "smoke", name, detail: cause ?? stderr.trim().split("\n")[0] ?? "failed" };
  } finally {
    rmSync(consumer, { recursive: true, force: true });
  }
}

const REPO_ROOT = fileURLToPath(new URL("../../", import.meta.url));

/** Where the one declaration of the layers lives, relative to a repository root. */
const LAYERS_JSON = "layers.json";

/**
 * The directories `layers.json` declares as the checkout of a layer that lives in a repository of its own (#3830).
 *
 * A layer is published from ITS repository (ADR 0040, #3126), so packing the checkout this host holds of it checks
 * something this release does not publish, and its `prepack` needs tooling the core's hosts need not have: on the lab
 * (no `pnpm` on PATH, #3141) that stopped `release:gate` at stage 5 with nine stages unread. `pnpm-workspace.yaml`
 * already says "a layer's clone is not a member of the core" (#3760); this is the same disagreement, in the gate's
 * own discovery.
 *
 * Read from the file directly, the way `scripts/lay-layer.ts` does, and NOT through `control`'s `layer-checkouts.mjs`:
 * that module holds a computed `import()` (`layerCodeVersion`), and every guard that declares a walk scope has this
 * file in its import closure, where a computed import is refused (`declared-walk-scope.test.ts`). It is still the one
 * declaration, read here and never restated. It sat in `packages/control/` until #3506 deleted that directory, and is at the root now.
 *
 * A layer with no `remote` is inside this repository's checkout, which publishes it, so it is not a layer checkout.
 * An absent or unreadable `layers.json` throws: answering "no layers" would pack them again, silently.
 *
 * @returns {string[]}
 */
function layerCheckoutDirs(): string[] {
  const file = join(REPO_ROOT, LAYERS_JSON);
  /** @type {{ layers: Record<string, { path: string, remote?: string }> }} */
  let manifest: { layers: Record<string, { path: string; remote?: string; }>; };
  try {
    manifest = JSON.parse(readFileSync(file, "utf8"));
  } catch (cause) {
    throw new Error(`gate:isolation cannot read ${file}, so it cannot tell which packages are a layer's checkout`, { cause });
  }
  return Object.values(manifest.layers).filter((layer) => layer.remote).map((layer) => resolve(REPO_ROOT, layer.path));
}

/** Is this directory a separate layer's checkout, which this repository's release does not publish? @param {string} dir */
function isLayerCheckout(dir: string) {
  return layerCheckoutDirs().includes(resolve(dir));
}

/**
 * The layer checkouts present here (holding a `package.json`) that discovery leaves out, by directory name: reported
 * beside the private count, because a gate that quietly covers less than you think is the failure this file exists to prevent.
 * @returns {string[]}
 */
export function leftOutLayerCheckouts(): string[] {
  return layerCheckoutDirs().filter((dir) => existsSync(join(dir, "package.json"))).map((dir) => basename(dir));
}

/** Every real package, so neither the gate nor the build can run against a stale hand-written list. */
export function allPackages() {
  const root = join(REPO_ROOT, "packages");
  if (!existsSync(root)) return [];
  return readdirSync(root, { withFileTypes: true })
    .filter((entry) => entry.isDirectory() && existsSync(join(root, entry.name, "package.json")))
    .map((entry) => join(root, entry.name))
    .filter((dir) => !isLayerCheckout(dir))
    // A `private` package is never published, so "can a consumer install this?" has no meaning for it and a
    // missing smoke test is not a defect. `@a11ign/lab` is private on purpose (ADR 0008): the corpus is
    // not distributable and the trainer would imply a reproducibility promise this project cannot make.
    // Skipping is announced by the caller rather than silent — a gate that quietly covers less than you think
    // is the failure mode this whole file exists to prevent.
    .filter((dir) => !JSON.parse(readFileSync(join(dir, "package.json"), "utf8")).private);
}

/** How many packages were skipped for being private — reported, so the gate's coverage is never overstated. */
function countPrivatePackages() {
  const root = join(REPO_ROOT, "packages");
  if (!existsSync(root)) return 0;
  return readdirSync(root, { withFileTypes: true })
    .filter((entry) => entry.isDirectory() && existsSync(join(root, entry.name, "package.json")))
    .filter((entry) => !isLayerCheckout(join(root, entry.name)))
    .filter((entry) => JSON.parse(readFileSync(join(root, entry.name, "package.json"), "utf8")).private)
    .length;
}

// NOT `file://${process.argv[1]}`: a template-literal URL does not percent-encode, so a checkout path
// containing a space makes this comparison false and `npm run gate:isolation` silently checks nothing —
// entry-points.test.ts's own "the guard is the exact comparison" test polices this idiom, but its
// discovery only matched packages/*.mjs|.ts until this file's own drift widened it to scripts/ too.
// realpathSync'd for the same reason every published bin needed it this session: harmless for a plain
// `node packages/guards/src/isolation-gate.ts` invocation, but this file is ALSO imported by test files under
// packages/, so the same guard idiom this repo now uses everywhere is worth using here too.
if (import.meta.url === pathToFileURL(process.argv[1] ? realpathSync(process.argv[1]) : "").href) {
  // Guarded per #164: --all, plus positional package dirs; npm flags go onward.
  refuseUnknownFlags(["--all"], { entry: import.meta.url, command: "node packages/guards/src/isolation-gate.ts" });
  const args = process.argv.slice(2);
  const targets = args.length === 0 || args[0] === "--all" ? allPackages() : args;
  if (args.length > 0 && args[0] !== "--all" && targets.length === 0) {
    process.stderr.write("usage: node packages/guards/src/isolation-gate.ts [--all | <package-dir>...]\n");
    process.exit(2);
  }
  const privateCount = args.length === 0 || args[0] === "--all" ? countPrivatePackages() : 0;
  if (privateCount) {
    process.stdout.write(`skipping ${privateCount} private package(s): never published, so nothing installs them\n`);
  }
  const leftOut = args.length === 0 || args[0] === "--all" ? leftOutLayerCheckouts() : [];
  if (leftOut.length) {
    process.stdout.write(`leaving out ${leftOut.length} layer checkout(s) (${leftOut.join(", ")}): `
      + "each is published from its own repository, so this release does not pack it\n");
  }
  if (targets.length === 0) {
    // Says so rather than reporting success over nothing. The gate's own correctness is asserted separately
    // by `packages/lab/src/packaging/isolation-gate.test.ts` against three fixtures, so an empty run here is honest
    // rather than unverified: there is genuinely nothing published yet (PLAN.md M1, zero moves).
    process.stdout.write("no packages under packages/ yet — nothing to gate (PLAN.md M1 is scaffolding only)\n");
    process.stdout.write("the gate itself is verified by packages/lab/src/packaging/isolation-gate.test.ts\n");
    process.exit(0);
  }
  // WHICH TOOL DID WHICH HALF, said in the run's own output (#2301): a dry run's log is what a reviewer reads
  // at the merging head, and "packed by pnpm, installed by npm" is the claim this gate exists to make true.
  process.stdout.write(`packing with pnpm ${runPnpm(["--version"], process.cwd()).trim()}; `
    + `installing as a consumer with npm ${runNpm(["--version"], process.cwd()).trim()}\n`);
  let failed = 0;
  let declined = 0;
  for (const target of targets) {
    const verdict = checkIsolation(target);
    if (verdict.skipped) declined += 1;
    else if (!verdict.ok) failed += 1;
    const tag = verdict.skipped ? "SKIP" : verdict.ok ? "ok  " : "FAIL";
    process.stdout.write(`  ${tag}  ${verdict.name ?? target}  ${verdict.detail}\n`);
  }
  // A declined package is NOT in the numerator. Counting it as usable is exactly the "reports success having
  // examined nothing" failure this file exists to prevent, so the coverage is stated rather than rounded up.
  process.stdout.write(`\n${targets.length - failed - declined}/${targets.length} package(s) usable when installed`
    + (declined ? `, ${declined} declined on ${process.platform} — run the gate on macOS for those\n` : "\n"));
  process.exit(failed ? 1 : 0);
}
